# Dependabot configuration for automated dependency updates
# This will create pull requests to update dependencies automatically

version: 2
updates:
  # Update GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 10
    labels:
      - "dependencies"
      - "github-actions"
    commit-message:
      prefix: "chore(deps)"
      
  # Update Bundler (Ruby) dependencies
  - package-ecosystem: "bundler"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 10
    labels:
      - "dependencies"
      - "ruby"
    commit-message:
      prefix: "chore(deps)"
    # Group minor and patch updates together
    groups:
      jekyll-ecosystem:
        patterns:
          - "jekyll*"
          - "github-pages"
        update-types:
          - "minor"
          - "patch"
    # Allow version updates for security patches
    allow:
      - dependency-type: "all"
    # Ignore major and minor version updates for Jekyll (GitHub Pages pins to 3.9.x)
    ignore:
      - dependency-name: "jekyll"
        update-types: 
          - "version-update:semver-major"
          - "version-update:semver-minor"
